### ISSUE TITLE
Some errors occurred！

### ISSUE THREAD

**Issue by W4nde3** [solei1/docker-for-XSS-plaform#2]
Step 15/23 : COPY my.cnf /etc/mysql/my.cnf
 ---> Using cache
 ---> 1303c1b50704
Step 16/23 : RUN rm /etc/apache2/apa2che.conf
 ---> Running in f01a782fa4b4
rm: cannot remove '/etc/apache2/apa2che.conf': No such file or directory
The command '/bin/sh -c rm /etc/apache2/apa2che.conf' returned a non-zero code: 1

**Comment by longuan** [comment]
一个小失误，已经更新了
